### PR TITLE
Add info for connection status + extract HTML into a template folder

### PR DESCRIPTION
**Pull request by remimarenco**
Hey,

So minor changes to begin with:
- I added a more informative text on mouseover button connection status
- I refactored by extracting the template from the Python to a proper html file

Let me know if it sounds good, and if not why ;)

### CODE REVIEW

**Comment by bgruening** [comment]
@remimarenco we did this all in one file to make it easier to patch Galaxy and to make it as non-intrusive as possible. I'm still not clear if this will be part of Galaxy one day.

I will merge this as it also makes our life easier to develop, but maybe we go back to one file at some point, not sure yet.

**Comment by remimarenco** [comment]
@bgruening Makes sense! I am not really used to the concept of "intrusive / non-intrusive code", but IMO if you put everything in one folder, it could be less intrusive too, and easier to review / test / have contributions. I was planning to add the .py file into that folder too.

Do you mind to explain me a bit more about this intrusive concept?

**Comment by bgruening** [comment]
There is no such concept. I'm just not sure if this will be accepted by upstream, so we have planned to make it as pluggable as possible. One folder is also ok.

**Comment by hexylena** [comment]
Oooh if this is what it sounds like.... well, I'm very excited ;)

**Comment by bgruening** [comment]
I would like to talk to you next week and if you have some time get you opinion on that. It's probably a security nightmare ;) But it is working great - and will change how user-interact with each other dramatically!

**Comment by hexylena** [comment]
Yes. Yes it should! I've been wanting this for a loooong time. :-)
6. jun. 2016 1.07 a.m. skrev "Björn Grüning" notifications@github.com:

**Pull request merged**
