### PR TITLE
Changes to the R package install recipe

### PR DESCRIPTION
**Pull request by yhoogstrate**
I have removed 1 bracket that was too much
I have removed piping to `/dev/null` (because that takes away the input for `grep`)
I have added a few extra grep scentences, which pop up when I tested with an incorrect INSTALL_DIR but a valid R pacakge.

I have tested this with:
BiocGenerics_0.14.0.tar.gz and correct install dir: "exit 0"
DOESNOTEXIST.tar.gz and correct install dir: "exit 1"
BiocGenerics_0.14.0.tar.gz and incorrect install dir: "exit 1"
DOESNOTEXIST.tar.gz and incorrect install dir: "exit 1"

The only worry I have is that this way of installing will have very sparse output in INSTALLATION.log. If the installation fails you will get one of these error messages:

```
  unable to install packages
Execution halted
```

or:

```
  installation of package ‘DOESNOTEXIST.tar.gz’ had non-zero exit status
exit 1
```

Which is not really helpful for debugging.

### CODE REVIEW

**Comment by bgruening** [comment]
`/dev/null` was to get rid of stdout. My intention was to only take `stderr`. 

The following is working here:

```
Rscript -e "install.packages(c('----BiocGenerics_0.14.0.tar.gz'),lib='/galaxy-central/tool_deps/deseq2/1.8.2/iuc/package_deseq2_1_8_2/00b14423d00f', repos=NULL, dependencies=FALSE)" 2>&1 >/dev/null | grep 'had non-zero' && echo 'error' || echo 'no error'
```

I'm also worried about grep, and egrep. These are not official Galaxy dependencies.

**Comment by yhoogstrate** [comment]
I have tested what you said about 2>&1 and >/dev/null and you are correct. It is not neccesairy to remove that part.

> The following is working here:

Please change `/galaxy-central/tool_deps/deseq2/1.8.2/iuc/package_deseq2_1_8_2/00b14423d00f` to `/dev/null` and test it again. It should throw an error but it doesn't. Dev null is not a realistic example, but something similar may happen when chmods or chowns are not being set properly (owned by root etc.) so I think this should be covered as well.

> I'm also worried about grep, and egrep. These are not official Galaxy dependencies.

That is a valid argument. I prefer to see the grepping within the galaxy code.

**Comment by bgruening** [comment]
@yhoogstrate what do you think about the following hack?

```
python -c "import sys, subprocess; command = '''PATH=$PATH:$R_HOME/bin; export PATH; R_LIBS=$R_LIBS; export R_LIBS; Rscript -e \"install.packages(c('-BiocGenerics_0.14.0.tar.gz'),lib='/galaxy-central/tool_deps/deseq2/1.8.2/iuc/package_deseq2_1_8_2/00b14423d00f', repos=NULL, dependencies=FALSE)\"'''; out = subprocess.check_output( command, shell=True ); [sys.exit( out ) for error_message in ['had non-zero exit status', 'unable to install packages', 'Execution halted'] if error_message in out]"
```

Let me know what you think about this and maybe we could write such a temp-python file into the cwd during the installation process and call this?
I'm in a meeting for the next hours. 

P.S. I was not able to get this running with shlex.split and shell=False in a one liner. If we create a temp file this is probably possible.

**Comment by yhoogstrate** [comment]
:+1: :+1: I really like this. It works like a charm here, and covers all issues stated above, and it keeps galaxy in control. It's not a 'dirty' hack either. I would not make temp files but create one static file, e.g.: `./scripts/tool_shed/recipes/SetupREnvironment_step_handler.py` and give it the package name as argument, but I am not so deep into the galaxy code to know what is the most appropriate solution. But  this way you can get rid of long lines (PEP8) and use the same script for debugging.

By the time we make the PR we should check for python2.6 and python3 compatibility.

Thanks again

**Pull request closed without merging**
