### PR TITLE
Use form view to build change password form

### PR DESCRIPTION
**Pull request by guerler**
This demonstrates how we can use existing ui libraries to build the preference forms (here: the change password form) and benefit from existing features e.g. buttons, operations etc. It avoids using global jquery selectors and custom html templates. Note that the redirect feature has been stripped since I think it would be better to determine it if necessary at the front end and not the api.

### CODE REVIEW

**Comment by bgruening** [comment]
ping @anuprulez

**Comment by anuprulez** [comment]
@guerler Thanks for reviewing and suggesting a better approach which reuses the existing features (views like form). Shall I go ahead and follow the same set of changes to convert all the mako files I have worked with? The redirect feature I did not get. Can you explain a bit more?
@bgruening

**Comment by guerler** [comment]
Awesome. That sounds great. Since you already have moved everything into js, its fairly easy to transform those just like I did with the change password form. Dont worry about the redirect for now and always feel free to ask me. Thanks a lot.

**Comment by bgruening** [comment]
You guys rock! Thanks @guerler for helping!

**Comment by anuprulez** [comment]
@guerler @bgruening  I have started making these changes to the user preferences views. I took up change communication view where a checkbox is needed. I tried to use a checkbox view (mvc/ui/ui-misc) and placed it under buttons attribute of Form view but it did not give correct result. I suppose this button view is for adding buttons and not for checkbox. 

I am not sure under which attribute of Form view I can insert checkbox view. Also, I searched the repository to look for any usage of this checkbox view but could not find one. Can you help?

```
buttons         : {
                    'save'  : new Ui.Checkbox.View({
                        name     : 'communication setting',
                        value    : '1',
                        onchange : function() { self.saveCommunicationChanges(); }
                    })
                }
```

**Comment by guerler** [comment]
The available parameters are listed here: https://github.com/galaxyproject/galaxy/blob/dev/client/galaxy/scripts/mvc/form/form-parameters.js#L15. You are probably looking for the `boolean` parameter but it should not be placed in the buttons, instead it should be added as one of the inputs like here: https://github.com/bgruening/galaxy/pull/16/files#diff-6253ed4f30bca9da2d066834c0efe769R10.

**Comment by bgruening** [comment]
@anuprulez a boolean is what you need. The checkbox can be replaced by any kind of boolean input :)

**Comment by anuprulez** [comment]
@guerler @bgruening I am working on Manage User Information screen and if you remember there is a widgets section inside this screen. So, in this widgets section, some dynamic chunk of HTML is coming from the database (for widgets) and is being processed. Now we are using the wrappers of Form and Inputs rather than directly creating the HTML, do you know if is there a way to directly process this dynamic HTML (not sure of what kind of HTML would it be) or is there a view which achieves this?

`'<label>'+ item_object['label'] + ':</label>' +
 item_object['html']`

Thanks!

**Edit**: Also, I could not find a simple way to add data using a label in a form view. This is needed to display address as plain text in the user addresses section. We should not use an input field for this.
I tried to fit addresses into help attribute of an input but that is just a hack. Similarly, for having buttons as Edit, Delete or Undelete apart from the form submit buttons added under buttons field inside a Form, I am not able to add like this:
`<input type='button'>`. 

Do we need to extend the form related views for including different parameter types (for inputs) or different tags (like labels)?

**Pull request merged**
