### PR TITLE
WIP, minor cleanup/fixes for show_structure

### PR DESCRIPTION
**Pull request by dannon**
Tweaking a few more things, hold off on merge for a sec.  Sorry for the delay on getting to this.

### CODE REVIEW

**Comment by dannon** [comment]
@bgruening Err.  Oops.  I toggled one branch I was working on but not the other, and ended up pushing this in directly on your branch.  Hope that's okay!  I'm going through the PR and doing a little refactoring to clean it up, and we should be able to get it in today.

**Comment by anuprulez** [comment]
@dannon thank you for helping on this PR!

**Comment by dannon** [comment]
@anuprulez Sure thing, sorry it took so long to get to, and thanks for all the work here!

**Comment by bgruening** [comment]
Thanks @dannon!

**Pull request merged**
