### PR TITLE
Try casting things

### PR DESCRIPTION
**Pull request by hexylena**
@anuprulez does this fix the issue? :( cc @bgruening

### CODE REVIEW

**Comment by anuprulez** [comment]
@erasche: Thanks for your help. But it did not work :(
@bgruening

**Comment by bgruening** [comment]
@anuprulez can you check you locale setting?

``` bash
 % locale
LANG=de_DE.UTF-8
LANGUAGE=de_DE:en_US:en
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=
```

And change it to UTF-8 if possible.

**Comment by hexylena** [comment]
Closing as not the solution.

**Comment by hexylena** [comment]
My best other guess was a bad key decryption? I'm not sure how that would happen though. :/

**Comment by anuprulez** [comment]
@bgruening: Yeah locale values have UTF-8

anupkumar@anupkumar-pc:~$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=

**Comment by bgruening** [comment]
I saw also some errors about not able to access `ws`. Can you make sure you have all firewalls deactivated and apparmor?
I'm lost here a little bit and running out of ideas as you see :(

**Comment by anuprulez** [comment]
I tried disabling ufw firewall and apparmor but they did not work. Further I looked into the code and found the **current_user.is_anonymous** is returning True and in the method **findUserByCookie**, the cookie value is None. As user information is not set properly, requests are not being sent I suppose. I am looking more into this why it is not able to fetch cookie information. May be because of browser settings. Not sure now.

**Comment by hexylena** [comment]
Aha! Okay, that makes more sense. If you `inspect element` and check out the network tab, is your galaxysession cookie being sent? I take it that it is not. You may need to set nginx or another proxy to place both galaxy and the chat server on the same IP+port

**Comment by anuprulez** [comment]
@bgruening @erasche Thanks a lot for your help! 

Now it works. But I am not sure which specific step solved it. Today I changed the URL to localhost instead of '127.0.0.1' and it started working both in Chrome and Firefox. Then it started working for '127.0.0.1' also. When I looked up the Resources tab in the developer tools of Chrome, there were two galaxysession cookies one each for localhost and 127.0.0.1. I assume they are same but do they resolve to different IP? Not sure. But at least it works now. :) :)

**Comment by hexylena** [comment]
Oh, that would do it. They're treated as different domains for purposes
of cookies.

**Pull request closed without merging**
